# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fd0645bec84be882885a1482366f242a05ae55cb017a29836fb1b5736c7c0bafef66df9dadf423042c3e7d9c5da7eb97c77ee3a488e2eb575f09bed03ed62e8

test:
  secret_key_base: 746e1fba8e2a5ded7e170e60a2a22d648096364dc44d4ad81cbe5045ee0c6087fbae5770cac39c40c724f1203b1a72a3ddb1b8f0e112709039dce1f6691b9967

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
